export enum FeatureIdent {
  DEV_MODE="DEV_MODE",
  SPACES = "SPACES",
  HELP = "HELP",
  OPEN_TABS = "OPEN_TABS",
  STANDALONE_APP = "STANDALONE_APP",
  NOTIFICATIONS = "NOTIFICATIONS",
  WINDOWS_MANAGEMENT = "WINDOWS_MANAGEMENT",
  ENTITY_MANAGER = "ENTITY_MANAGER",
  API_MANAGER = "API_MANAGER",
}

export enum FeatureType {
  RECOMMENDED = "RECOMMENDED",
  OPTIONAL = "OPTIONAL",
  EXPERIMENTAL = "EXPERIMENTAL",
  PLANNED = "PLANNED",
  DISABLED = "DISABLED",
  INTERNAL = "INTERNAL"
}
